name: ci
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19.4
      - uses: golangci/golangci-lint-action@v3.4.0
        with:
          args: "--out-${NO_FUTURE}format colored-line-number"
